# Generated by Django 6.0.1 on 2026-01-31 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('NIT', 'NIT'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('TI', 'Tarjeta de Identidad'), ('RC', 'Registro Civil'), ('TE', 'Tarjeta de Extranjería'), ('DIE', 'Doc. Identificación Extranjero')], max_length=3, verbose_name='Tipo Doc.')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número Doc.')),
                ('digito_verificacion', models.CharField(blank=True, max_length=1, null=True, verbose_name='DV')),
                ('primer_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('segundo_apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('primer_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('otros_nombres', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_razon_social', models.CharField(max_length=255, verbose_name='Nombre o Razón Social')),
                ('tipo_tercero', models.CharField(choices=[('CLI', 'Cliente'), ('PRO', 'Proveedor'), ('EMP', 'Empleado'), ('SOC', 'Socio/Accionista'), ('OTR', 'Otro')], default='OTR', max_length=3)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_municipio', models.CharField(blank=True, max_length=5, null=True, verbose_name='Cód. Municipio')),
                ('codigo_departamento', models.CharField(blank=True, max_length=2, null=True, verbose_name='Cód. Dpto')),
                ('codigo_pais', models.CharField(default='169', max_length=3, verbose_name='Cód. País')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceros', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Tercero',
                'verbose_name_plural': 'Terceros',
                'ordering': ['nombre_razon_social'],
                'unique_together': {('empresa', 'numero_documento')},
            },
        ),
    ]
