# Generated by Django 5.2.11 on 2026-02-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0002_terceros_globales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='es_autoretenedor',
            field=models.BooleanField(default=False, verbose_name='Autoretenedor'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='es_declarante',
            field=models.BooleanField(default=True, verbose_name='Declarante de Renta'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='es_gran_contribuyente',
            field=models.BooleanField(default=False, verbose_name='Gran Contribuyente'),
        ),
    ]
