# Generated by Django 5.2.13 on 2026-06-26 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('terceros', '0003_tercero_es_autoretenedor_tercero_es_declarante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tercero',
            name='es_compartido',
            field=models.BooleanField(default=False, verbose_name='Compartido (todas las empresas)'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='regimen_simple',
            field=models.BooleanField(default=False, verbose_name='Régimen Simple de Tributación'),
        ),
        migrations.CreateModel(
            name='EmpresaTercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terceros_rel', to='empresas.empresa')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas_rel', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'Empresa-Tercero',
                'verbose_name_plural': 'Empresas-Terceros',
                'unique_together': {('empresa', 'tercero')},
            },
        ),
    ]
