# Generated by Django 6.0.2 on 2026-02-09 18:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('terceros', '0002_terceros_globales'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametrosNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='Año')),
                ('smlv', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='SMLV')),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Auxilio de transporte')),
                ('salud_empleado', models.DecimalField(decimal_places=3, default=4.0, max_digits=5, verbose_name='% Salud empleado')),
                ('pension_empleado', models.DecimalField(decimal_places=3, default=4.0, max_digits=5, verbose_name='% Pensión empleado')),
                ('fsp_empleado', models.DecimalField(decimal_places=3, default=0.0, help_text='Aplica a salarios >= 4 SMLV', max_digits=5, verbose_name='% Fondo Solidaridad Pensional')),
                ('salud_empleador', models.DecimalField(decimal_places=3, default=8.5, max_digits=5, verbose_name='% Salud empleador')),
                ('pension_empleador', models.DecimalField(decimal_places=3, default=12.0, max_digits=5, verbose_name='% Pensión empleador')),
                ('arl_i', models.DecimalField(decimal_places=3, default=0.522, max_digits=5, verbose_name='% ARL Nivel I')),
                ('arl_ii', models.DecimalField(decimal_places=3, default=1.044, max_digits=5, verbose_name='% ARL Nivel II')),
                ('arl_iii', models.DecimalField(decimal_places=3, default=2.436, max_digits=5, verbose_name='% ARL Nivel III')),
                ('arl_iv', models.DecimalField(decimal_places=3, default=4.35, max_digits=5, verbose_name='% ARL Nivel IV')),
                ('arl_v', models.DecimalField(decimal_places=3, default=6.96, max_digits=5, verbose_name='% ARL Nivel V')),
                ('caja_compensacion', models.DecimalField(decimal_places=3, default=4.0, max_digits=5, verbose_name='% Caja compensación')),
                ('sena', models.DecimalField(decimal_places=3, default=2.0, max_digits=5, verbose_name='% SENA')),
                ('icbf', models.DecimalField(decimal_places=3, default=3.0, max_digits=5, verbose_name='% ICBF')),
                ('factor_prima', models.DecimalField(decimal_places=4, default=Decimal('8.3333'), help_text='8.3333% = 30 días / 360', max_digits=5, verbose_name='% Prima mensual')),
                ('factor_cesantias', models.DecimalField(decimal_places=4, default=Decimal('8.3333'), max_digits=5, verbose_name='% Cesantías mensual')),
                ('factor_int_cesantias', models.DecimalField(decimal_places=3, default=Decimal('12.000'), help_text='12% anual sobre cesantías', max_digits=5, verbose_name='% Intereses sobre cesantías')),
                ('factor_vacaciones', models.DecimalField(decimal_places=4, default=Decimal('4.1667'), help_text='15 días / 360 = 4.1667%', max_digits=5, verbose_name='% Vacaciones mensual')),
                ('recargo_extra_diurna', models.DecimalField(decimal_places=2, default=25, max_digits=5, verbose_name='% Recargo hora extra diurna')),
                ('recargo_extra_nocturna', models.DecimalField(decimal_places=2, default=75, max_digits=5, verbose_name='% Recargo hora extra nocturna')),
                ('recargo_dominical_diurna', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='% Recargo dominical/festiva diurna')),
                ('recargo_dominical_nocturna', models.DecimalField(decimal_places=2, default=150, max_digits=5, verbose_name='% Recargo dominical/festiva nocturna')),
                ('recargo_nocturno', models.DecimalField(decimal_places=2, default=35, max_digits=5, verbose_name='% Recargo nocturno ordinario')),
            ],
            options={
                'verbose_name': 'Parámetros de Nómina',
                'verbose_name_plural': 'Parámetros de Nómina',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contrato', models.CharField(choices=[('IND', 'Indefinido'), ('FIJ', 'Fijo'), ('OBR', 'Obra o labor'), ('PRE', 'Prestación de servicios')], default='IND', max_length=3)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de ingreso')),
                ('fecha_retiro', models.DateField(blank=True, null=True, verbose_name='Fecha de retiro')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salario base mensual')),
                ('salario_integral', models.BooleanField(default=False, help_text='Si es True, el 70% es factor salarial y 30% factor prestacional.', verbose_name='Salario integral')),
                ('nivel_arl', models.PositiveSmallIntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], default=1, verbose_name='Nivel ARL')),
                ('eps', models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS')),
                ('afp', models.CharField(blank=True, max_length=100, null=True, verbose_name='AFP (Fondo de pensiones)')),
                ('caja_compensacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Caja de compensación')),
                ('arl_nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='ARL')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('centro_costo', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='empresas.empresa')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleo', to='terceros.tercero')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['tercero__nombre_razon_social'],
                'unique_together': {('empresa', 'tercero')},
            },
        ),
        migrations.CreateModel(
            name='LiquidacionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=30)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salario_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('horas_extras', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recargos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('comisiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_devengados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salud_empleado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_empleado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fsp', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Fondo Solidaridad Pensional')),
                ('retencion_fuente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('libranzas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salud_empleador', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pension_empleador', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arl', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('caja_compensacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sena', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('icbf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provision_prima', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provision_cesantias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provision_int_cesantias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('provision_vacaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('costo_empresa', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='nomina.empleado')),
            ],
            options={
                'verbose_name': 'Liquidación de Empleado',
                'verbose_name_plural': 'Liquidaciones de Empleados',
            },
        ),
        migrations.CreateModel(
            name='DetalleHorasExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('HED', 'Hora extra diurna'), ('HEN', 'Hora extra nocturna'), ('HEDD', 'Hora extra dominical diurna'), ('HEDN', 'Hora extra dominical nocturna'), ('RN', 'Recargo nocturno'), ('RDD', 'Recargo dominical diurno'), ('RDN', 'Recargo dominical nocturno')], max_length=4)),
                ('cantidad_horas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('valor_hora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_recargo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_horas', to='nomina.liquidacionempleado')),
            ],
            options={
                'verbose_name': 'Detalle Horas Extra',
                'verbose_name_plural': 'Detalle Horas Extra',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MEN', 'Mensual'), ('Q1', 'Primera quincena'), ('Q2', 'Segunda quincena')], default='MEN', max_length=3)),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mes')),
                ('fecha_liquidacion', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('liquidada', 'Liquidada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_costo_empresa', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('empresa', 'anio', 'mes', 'tipo')},
            },
        ),
        migrations.AddField(
            model_name='liquidacionempleado',
            name='nomina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones', to='nomina.nomina'),
        ),
        migrations.AlterUniqueTogether(
            name='liquidacionempleado',
            unique_together={('nomina', 'empleado')},
        ),
    ]
