# Generated by Django 6.0.2 on 2026-02-09 22:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_nomina_asiento_contable'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='aportes_afc',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Art. 126-4 ET — Renta exenta, hasta 25% del ingreso', max_digits=12, verbose_name='Aportes AFC mensual'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='aportes_voluntarios_pension',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Art. 126-1 ET — Renta exenta, hasta 25% del ingreso', max_digits=12, verbose_name='Aportes voluntarios pensión mensual'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='deduccion_medicina_prepagada',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Art. 387 ET — Hasta 16 UVT mensuales', max_digits=12, verbose_name='Medicina prepagada mensual'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='deduccion_vivienda',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Art. 119/387 ET — Hasta 100 UVT mensuales', max_digits=12, verbose_name='Intereses vivienda mensual'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tiene_dependientes',
            field=models.BooleanField(default=False, help_text='Art. 387 ET — Hijos <18, 18-25 estudiando, cónyuge, padres/hermanos sin ingresos', verbose_name='¿Tiene dependientes?'),
        ),
        migrations.AddField(
            model_name='parametrosnomina',
            name='uvt',
            field=models.DecimalField(decimal_places=2, default=Decimal('52374'), max_digits=12, verbose_name='UVT'),
        ),
    ]
