# Generated by Django 6.0.2 on 2026-02-09 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_movimientocontable_tercero'),
        ('empresas', '0001_initial'),
        ('nomina', '0003_retencion_fuente_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiquidacionContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('RENUNCIA', 'Renuncia voluntaria'), ('DESPIDO_JUSTA', 'Despido con justa causa'), ('DESPIDO_INJUSTA', 'Despido sin justa causa'), ('MUTUO', 'Mutuo acuerdo'), ('TERMINACION_FIJO', 'Terminación contrato fijo'), ('FIN_OBRA', 'Finalización obra o labor'), ('MUERTE', 'Muerte del trabajador')], max_length=20)),
                ('fecha_retiro', models.DateField(verbose_name='Fecha de retiro')),
                ('fecha_liquidacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('liquidada', 'Liquidada'), ('pagada', 'Pagada'), ('anulada', 'Anulada')], default='borrador', max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_ingreso', models.DateField(null=True)),
                ('tipo_contrato', models.CharField(default='IND', max_length=3)),
                ('salario_integral', models.BooleanField(default=False)),
                ('fecha_fin_contrato', models.DateField(blank=True, help_text='Solo para contratos a término fijo: fecha de vencimiento', null=True)),
                ('dias_vacaciones_disfrutados', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Días de vacaciones ya disfrutados')),
                ('dias_ultimo_mes', models.PositiveSmallIntegerField(default=0)),
                ('salario_proporcional', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auxilio_transporte_prop', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_vacaciones_pendientes', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('vacaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_prima', models.PositiveSmallIntegerField(default=0)),
                ('prima_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_cesantias', models.PositiveSmallIntegerField(default=0)),
                ('cesantias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('intereses_cesantias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('indemnizacion', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('retencion_fuente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduccion_salud', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deduccion_pension', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('otros_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_devengado', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('neto_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liquidacion_contrato_origen', to='contabilidad.asientocontable')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones_contrato', to='nomina.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidaciones_contrato', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Liquidación de Contrato',
                'verbose_name_plural': 'Liquidaciones de Contrato',
                'ordering': ['-fecha_retiro'],
            },
        ),
    ]
