# Generated by Django 6.0.2 on 2026-02-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_liquidacion_contrato'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='trabajo_remoto',
            field=models.BooleanField(default=False, help_text='Si es True, no se paga auxilio de transporte (Ley 1221/2008)', verbose_name='Trabajo remoto / teletrabajo'),
        ),
        migrations.AddField(
            model_name='liquidacioncontrato',
            name='trabajo_remoto',
            field=models.BooleanField(default=False),
        ),
    ]
