# Generated by Django 6.0.2 on 2026-02-09 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_movimientocontable_tercero'),
        ('empresas', '0001_initial'),
        ('nomina', '0005_trabajo_remoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CesantiasAnuales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('fecha_liquidacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('liquidada', 'Liquidada'), ('consignada', 'Consignada al fondo')], default='borrador', max_length=12)),
                ('total_cesantias', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_intereses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cesantias_origen', to='contabilidad.asientocontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cesantias', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Cesantías Anuales',
                'verbose_name_plural': 'Cesantías Anuales',
                'ordering': ['-anio'],
                'unique_together': {('empresa', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='PrimaSemestral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('semestre', models.PositiveSmallIntegerField(choices=[(1, 'Primer semestre (Jun)'), (2, 'Segundo semestre (Dic)')])),
                ('fecha_liquidacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('liquidada', 'Liquidada'), ('pagada', 'Pagada')], default='borrador', max_length=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prima_origen', to='contabilidad.asientocontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primas', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Prima Semestral',
                'verbose_name_plural': 'Primas Semestrales',
                'ordering': ['-anio', '-semestre'],
                'unique_together': {('empresa', 'anio', 'semestre')},
            },
        ),
        migrations.CreateModel(
            name='Vacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias_habiles', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('disfrutada', 'Disfrutada'), ('rechazada', 'Rechazada')], default='solicitada', max_length=12)),
                ('notas', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacaciones', to='nomina.empleado')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacaciones', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Vacación',
                'verbose_name_plural': 'Vacaciones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCesantias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=0)),
                ('valor_cesantias', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_intereses', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cesantias', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.cesantiasanuales')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.empleado')),
            ],
            options={
                'unique_together': {('cesantias', 'empleado')},
            },
        ),
        migrations.CreateModel(
            name='DetallePrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario_base', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('auxilio_transporte', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dias_trabajados', models.PositiveSmallIntegerField(default=0)),
                ('valor_prima', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.empleado')),
                ('prima', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.primasemestral')),
            ],
            options={
                'unique_together': {('prima', 'empleado')},
            },
        ),
    ]
