# Generated by Django 6.0.1 on 2026-01-31 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('terceros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=0, verbose_name='Número de Asiento')),
                ('fecha', models.DateField(verbose_name='Fecha del Asiento')),
                ('fiscal_year', models.PositiveIntegerField(db_index=True, default=0)),
                ('fiscal_period', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('concepto', models.CharField(max_length=500, verbose_name='Concepto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('descripcion_adicional', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('vigente', 'Vigente'), ('anulado', 'Anulado')], default='vigente', max_length=10)),
                ('anulado_en', models.DateTimeField(blank=True, null=True)),
                ('anulacion_motivo', models.TextField(blank=True, null=True)),
                ('ajusta_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes', to='contabilidad.asientocontable')),
                ('anulado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos', to='empresas.empresa', verbose_name='Empresa')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero', verbose_name='Tercero')),
            ],
            options={
                'verbose_name': 'Asiento Contable',
                'verbose_name_plural': 'Asientos Contables',
                'ordering': ['-fecha', '-numero'],
                'unique_together': {('empresa', 'fiscal_year', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='CuentaBase',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Cuenta')),
                ('nivel', models.PositiveSmallIntegerField(default=1, verbose_name='Nivel')),
                ('naturaleza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Naturaleza')),
                ('tipo', models.CharField(choices=[('Clase', 'Clase'), ('Grupo', 'Grupo'), ('Cuenta', 'Cuenta'), ('Subcuenta', 'Subcuenta'), ('Auxiliar', 'Auxiliar')], default='Cuenta', max_length=20, verbose_name='Tipo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='contabilidad.cuentabase')),
            ],
            options={
                'verbose_name': 'Cuenta PUC Base',
                'verbose_name_plural': 'Plan de Cuentas Base',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la Cuenta')),
                ('nivel', models.PositiveSmallIntegerField(default=4, verbose_name='Nivel')),
                ('naturaleza', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], default='D', max_length=1, verbose_name='Naturaleza')),
                ('tipo', models.CharField(choices=[('Clase', 'Clase'), ('Grupo', 'Grupo'), ('Cuenta', 'Cuenta'), ('Subcuenta', 'Subcuenta'), ('Auxiliar', 'Auxiliar')], default='Auxiliar', max_length=20, verbose_name='Tipo')),
                ('clasificacion_niif', models.CharField(blank=True, max_length=100, null=True)),
                ('seccion_niif', models.CharField(blank=True, max_length=50, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='empresas.empresa', verbose_name='Empresa')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='contabilidad.cuenta')),
                ('cuenta_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_empresa', to='contabilidad.cuentabase', verbose_name='Cuenta PUC Base')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Plan de Cuentas',
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Débito')),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédito')),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidad.cuenta')),
            ],
            options={
                'verbose_name': 'Movimiento Contable',
                'verbose_name_plural': 'Movimientos Contables',
                'ordering': ['asiento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(verbose_name='Año')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cierre', 'En Cierre'), ('cerrado', 'Cerrado')], default='abierto', max_length=10)),
                ('ajustes_inicio', models.DateField(verbose_name='Inicio ventana ajustes')),
                ('ajustes_fin', models.DateField(verbose_name='Fin ventana ajustes')),
                ('habilitar_mes13', models.BooleanField(default=True)),
                ('requiere_pins_en_ajustes', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='empresas.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Periodo Contable',
                'verbose_name_plural': 'Periodos Contables',
                'ordering': ['empresa', '-anio'],
                'unique_together': {('empresa', 'anio')},
            },
        ),
    ]
