# Generated by Django 5.2.10 on 2026-02-02 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('fecha_corte', models.DateField(verbose_name='Fecha de Corte')),
                ('saldo_extracto', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo según Extracto Bancario')),
                ('saldo_libros', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo según Libros')),
                ('saldo_conciliado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Conciliado')),
                ('cheques_pendientes', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('depositos_transito', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notas_debito_banco', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('notas_credito_banco', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('conciliado', 'Conciliado'), ('aprobado', 'Aprobado')], default='borrador', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('cuenta_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conciliaciones', to='contabilidad.cuenta', verbose_name='Cuenta Contable del Banco')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Conciliación Bancaria',
                'verbose_name_plural': 'Conciliaciones Bancarias',
                'ordering': ['-año', '-mes'],
                'unique_together': {('empresa', 'cuenta_banco', 'año', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='MovimientoExtracto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('debito', 'Débito (Salida)'), ('credito', 'Crédito (Entrada)')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('conciliado', 'Conciliado'), ('no_aplica', 'No Aplica')], default='pendiente', max_length=15)),
                ('es_cheque_pendiente', models.BooleanField(default=False)),
                ('es_deposito_transito', models.BooleanField(default=False)),
                ('es_nota_debito', models.BooleanField(default=False)),
                ('es_nota_credito', models.BooleanField(default=False)),
                ('observacion', models.CharField(blank=True, max_length=255, null=True)),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_extracto', to='contabilidad.conciliacionbancaria')),
                ('movimiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_extracto', to='contabilidad.movimientocontable')),
            ],
            options={
                'verbose_name': 'Movimiento de Extracto',
                'verbose_name_plural': 'Movimientos de Extracto',
                'ordering': ['fecha', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PartidaConciliatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cheque_pendiente', 'Cheque girado no cobrado'), ('deposito_transito', 'Depósito en tránsito'), ('nota_debito_banco', 'Nota débito del banco no registrada'), ('nota_credito_banco', 'Nota crédito del banco no registrada'), ('error_banco', 'Error del banco'), ('error_libros', 'Error en libros'), ('otro', 'Otro')], max_length=25)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15)),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_resolucion', models.DateField(blank=True, null=True)),
                ('conciliacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_conciliatorias', to='contabilidad.conciliacionbancaria')),
                ('movimiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.movimientocontable')),
                ('movimiento_extracto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.movimientoextracto')),
            ],
            options={
                'verbose_name': 'Partida Conciliatoria',
                'verbose_name_plural': 'Partidas Conciliatorias',
                'ordering': ['tipo', 'fecha'],
            },
        ),
    ]
