# Generated by Django 5.2.10 on 2026-02-02 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_conciliacionbancaria_movimientoextracto_and_more'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaNotaEEFF',
            fields=[
                ('tipo_nota', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('titulo_default', models.CharField(max_length=255)),
                ('contenido_plantilla', models.TextField(help_text='Usar marcadores como {empresa}, {nit}, {año}, {saldo_efectivo}, etc.')),
                ('seccion_niif', models.CharField(blank=True, max_length=100, null=True)),
                ('obligatoria', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plantilla de Nota',
                'verbose_name_plural': 'Plantillas de Notas',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='NotaEstadoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.PositiveIntegerField()),
                ('tipo_nota', models.CharField(choices=[('general', '1. Información General'), ('politicas', '2. Políticas Contables'), ('efectivo', '3. Efectivo y Equivalentes'), ('cuentas_cobrar', '4. Cuentas por Cobrar'), ('inventarios', '5. Inventarios'), ('propiedad_planta', '6. Propiedad, Planta y Equipo'), ('intangibles', '7. Activos Intangibles'), ('cuentas_pagar', '8. Cuentas por Pagar'), ('obligaciones', '9. Obligaciones Financieras'), ('impuestos', '10. Impuestos'), ('provisiones', '11. Provisiones y Contingencias'), ('patrimonio', '12. Patrimonio'), ('ingresos', '13. Ingresos Operacionales'), ('costos_gastos', '14. Costos y Gastos'), ('partes_relacionadas', '15. Partes Relacionadas'), ('hechos_posteriores', '16. Hechos Posteriores'), ('otras', '17. Otras Revelaciones')], max_length=30)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField(blank=True, null=True)),
                ('datos_json', models.JSONField(blank=True, null=True)),
                ('incluir_en_reporte', models.BooleanField(default=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_eeff', to='empresas.empresa')),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota a Estados Financieros',
                'verbose_name_plural': 'Notas a Estados Financieros',
                'ordering': ['año', 'orden', 'numero'],
                'unique_together': {('empresa', 'año', 'tipo_nota')},
            },
        ),
    ]
