# Generated by Django 5.2.10 on 2026-02-02 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_plantillanotaeeff_notaestadofinanciero'),
        ('empresas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('mensual', 'Cierre Mensual'), ('anual', 'Cierre Anual')], max_length=10)),
                ('año', models.IntegerField()),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('fecha_cierre', models.DateField()),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('total_ingresos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_costos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_gastos', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('resultado_ejercicio', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('estado', models.CharField(choices=[('cerrado', 'Cerrado'), ('reabierto', 'Reabierto')], default='cerrado', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('asiento_cierre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierre_origen', to='contabilidad.asientocontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres', to='empresas.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-año', '-mes'],
                'unique_together': {('empresa', 'tipo', 'año', 'mes')},
            },
        ),
    ]
