# Generated by Django 5.2.11 on 2026-02-12 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_movimientocontable_tercero'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('concepto_pago', models.CharField(max_length=200)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('norma', models.CharField(blank=True, max_length=100)),
                ('base_minima_pesos', models.DecimalField(decimal_places=0, default=0, help_text='0 = aplica sobre 100% sin mínimo', max_digits=18)),
                ('tarifa', models.DecimalField(decimal_places=2, help_text='Porcentaje. Ej: 2.5 para 2.5%', max_digits=5)),
                ('cuenta_retencion', models.CharField(blank=True, help_text='Código cuenta retención sugerida (ej: 236540)', max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Concepto de Retención',
                'verbose_name_plural': 'Conceptos de Retención',
                'ordering': ['categoria', 'codigo'],
            },
        ),
    ]
