# Generated by Django 5.2.11 on 2026-02-12 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0007_bitacoraauditoria'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='asientocontable',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='tipo_comprobante',
            field=models.CharField(choices=[('RC', 'Recibo de Caja'), ('CE', 'Comprobante de Egreso'), ('FV', 'Factura de Venta'), ('FC', 'Factura de Compra'), ('NM', 'Nómina'), ('AJ', 'Ajustes'), ('NC', 'Nota Crédito'), ('ND', 'Nota Débito'), ('CI', 'Comprobante de Ingreso'), ('OT', 'Otros')], default='OT', max_length=3, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AlterUniqueTogether(
            name='asientocontable',
            unique_together={('empresa', 'tipo_comprobante', 'fiscal_year', 'numero')},
        ),
    ]
