# Generated by Django 5.2.11 on 2026-02-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_bitacoraauditoria'),
        ('contabilidad', '0008_alter_asientocontable_unique_together_and_more'),
    ]

    operations = [
    ]
