# Generated by Django 5.2.11 on 2026-02-14 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0009_merge_20260212_1622'),
        ('empresas', '0001_initial'),
        ('terceros', '0003_tercero_es_autoretenedor_tercero_es_declarante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la plantilla')),
                ('concepto', models.CharField(blank=True, max_length=500, verbose_name='Concepto base')),
                ('tipo_comprobante', models.CharField(default='OT', max_length=3, verbose_name='Tipo comprobante')),
                ('notas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_asiento', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Plantilla de Asiento',
                'ordering': ['nombre'],
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='AsientoProgramado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_del_mes', models.PositiveSmallIntegerField(help_text='Día en que se genera el borrador (1-28)', verbose_name='Día del mes')),
                ('activo', models.BooleanField(default=True)),
                ('ultimo_generado', models.DateField(blank=True, help_text='Última fecha en que se generó un borrador', null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asientos_programados', to='empresas.empresa')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programaciones', to='contabilidad.plantillaasiento')),
            ],
            options={
                'verbose_name': 'Asiento Programado',
                'verbose_name_plural': 'Asientos Programados',
            },
        ),
        migrations.CreateModel(
            name='PlantillaLinea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('debito', 'Débito'), ('credito', 'Crédito')], max_length=7)),
                ('monto', models.DecimalField(decimal_places=2, default=0, help_text='Monto fijo. 0 = se llena manualmente al usar la plantilla.', max_digits=15)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cuenta')),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='contabilidad.plantillaasiento')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='terceros.tercero')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
    ]
