# Generated by Django 5.2.13 on 2026-06-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_plantillaasiento_asientoprogramado_plantillalinea'),
        ('terceros', '0003_tercero_es_autoretenedor_tercero_es_declarante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientocontable',
            name='tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='terceros.tercero', verbose_name='Tercero'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo_comprobante',
            field=models.CharField(choices=[('RC', 'Recibo de Caja'), ('CE', 'Comprobante de Egreso'), ('FV', 'Factura de Venta'), ('FC', 'Factura de Compra'), ('NM', 'Nómina'), ('AJ', 'Ajustes'), ('NC', 'Nota Crédito'), ('ND', 'Nota Débito'), ('CI', 'Comprobante de Ingreso'), ('AP', 'Apertura'), ('OT', 'Otros')], default='OT', max_length=3, verbose_name='Tipo de Comprobante'),
        ),
    ]
