# Generated by Django 5.2.13 on 2026-06-26 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_alter_asientocontable_tercero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='es_estandar',
            field=models.BooleanField(default=False, verbose_name='Estándar (copiar a todas las empresas)'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='naturaleza',
            field=models.CharField(blank=True, choices=[('D', 'Débito'), ('C', 'Crédito')], default='', max_length=1, verbose_name='Naturaleza'),
        ),
    ]
