# Generated by Django 6.0.1 on 2026-01-31 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(help_text='Formato: 123456789-0', max_length=15, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=255, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre Comercial')),
                ('tipo_persona', models.CharField(choices=[('N', 'Persona Natural'), ('J', 'Persona Jurídica')], default='J', max_length=1)),
                ('regimen', models.CharField(choices=[('RC', 'Responsable de IVA'), ('RS', 'No Responsable de IVA'), ('GC', 'Gran Contribuyente')], default='RC', max_length=2)),
                ('grupo_niif', models.CharField(choices=[('1', 'Grupo 1 - NIIF Plenas'), ('2', 'Grupo 2 - NIIF para Pymes'), ('3', 'Grupo 3 - Contabilidad Simplificada')], default='2', max_length=1)),
                ('tipo_contribuyente', models.CharField(choices=[('GC', 'Gran Contribuyente'), ('AR', 'Autorretenedor'), ('RC', 'Responsable de IVA'), ('NR', 'No Responsable de IVA')], default='RC', max_length=2)),
                ('actividad_principal', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código CIIU')),
                ('descripcion_actividad', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_municipio', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código DANE Municipio')),
                ('codigo_departamento', models.CharField(blank=True, max_length=2, null=True, verbose_name='Código DANE Dpto')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('representante_legal', models.CharField(blank=True, max_length=255, null=True)),
                ('documento_representante', models.CharField(blank=True, max_length=20, null=True)),
                ('contador_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('contador_documento', models.CharField(blank=True, max_length=20, null=True)),
                ('contador_tarjeta', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tarjeta Profesional')),
                ('fecha_inicio_actividades', models.DateField(blank=True, null=True)),
                ('periodo_contable_actual', models.PositiveIntegerField(default=2025)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_contador', models.CharField(blank=True, max_length=10, null=True)),
                ('pin_gerente', models.CharField(blank=True, max_length=10, null=True)),
                ('politicas_contables', models.TextField(blank=True, null=True)),
                ('notas_eeff_plantilla', models.TextField(blank=True, null=True)),
                ('logo', models.BinaryField(blank=True, null=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresas',
            },
        ),
    ]
